FROM node:slim

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./

ARG NEXT_PUBLIC_API_URL=http://backend:8686
ARG NEXT_PUBLIC_REMOTE_PATTERNS=https://backend:8686
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_REMOTE_PATTERNS=$NEXT_PUBLIC_REMOTE_PATTERNS

RUN npm install dotenv

ENV NODE_ENV=production

EXPOSE 3000

COPY <<EOF /app/start.sh
#!/bin/sh
npm run build
npm start
EOF

RUN chmod +x /app/start.sh

CMD ["/app/start.sh"]